[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/product/*"
  to = "/.netlify/functions/nextServer/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200